CREATE DATABASE IF NOT EXISTS `test_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON `test_db`.* TO '${MYSQL_USER}'@'%';

CREATE USER '${MYSQL_REPLICATION_USER}'@'%' IDENTIFIED WITH 'mysql_native_password' BY '${MYSQL_REPLICATION_PASSWORD}';
GRANT REPLICATION SLAVE ON *.* TO '${MYSQL_REPLICATION_USER}'@'%';

FLUSH PRIVILEGES; 